#!/usr/bin/env python3
"""Build the isolated Wine worker config and exact Nginx alias routes."""

from __future__ import annotations

import argparse
import configparser
import os
import re
import tempfile
from pathlib import Path


ALIAS_RE = re.compile(r"^[A-Za-z0-9_]+$")


def windows_path(value: str) -> str:
    if not value:
        return value
    if re.match(r"^[A-Za-z]:[\\/]", value):
        return value
    if not value.startswith("/"):
        raise ValueError(f"worker filesystem path must be absolute: {value!r}")
    return "Z:" + value.replace("/", "\\")


def remote_database(value: str, host: str) -> str:
    if not value:
        raise ValueError("database path is empty")
    if re.match(r"^[^/\\:]+:", value):
        return value
    if not value.startswith("/"):
        raise ValueError(f"database path must be absolute: {value!r}")
    return f"{host}:{value}"


def load_config(path: Path) -> configparser.ConfigParser:
    config = configparser.ConfigParser(interpolation=None, strict=True)
    config.optionxform = str
    with path.open("r", encoding="utf-8-sig") as stream:
        config.read_file(stream)
    if "Server" not in config:
        raise ValueError("source config has no [Server] section")
    return config


def build_worker_config(
    source: configparser.ConfigParser, *, port: int, firebird_host: str
) -> configparser.ConfigParser:
    result = configparser.ConfigParser(interpolation=None, strict=True)
    result.optionxform = str
    result["Server"] = dict(source["Server"])
    result["Server"]["Address"] = "127.0.0.1"
    result["Server"]["Port"] = str(port)
    result["Server"]["UseSSL"] = "False"
    result["Server"]["Firebird"] = "5"
    result["Server"]["ShowConnections"] = "False"
    result["Server"]["WindowsWorkerMode"] = "True"

    for section in source.sections():
        if section == "Server":
            continue
        values = dict(source[section])
        if section.lower().startswith("provider:"):
            result[section] = values
            continue
        if not ALIAS_RE.fullmatch(section):
            raise ValueError(f"database alias is not routable: {section!r}")
        values["Database"] = remote_database(
            values.get("Database", ""), firebird_host
        )
        if values.get("Templates"):
            values["Templates"] = windows_path(values["Templates"])
        result[section] = values
    return result


def build_routes(source: configparser.ConfigParser, upstream: str) -> str:
    blocks = [
        "# Generated by DataExpress Windows worker. Do not edit by hand.",
    ]
    for section in source.sections():
        if section == "Server" or section.lower().startswith("provider:"):
            continue
        if not ALIAS_RE.fullmatch(section):
            raise ValueError(f"database alias is not routable: {section!r}")
        alias = section.lower()
        blocks.extend(
            [
                f"location ^~ /{alias}/ {{",
                "    limit_req zone=dx_requests burst=80 nodelay;",
                "    limit_req zone=dx_logins burst=10 nodelay;",
                f"    proxy_pass http://{upstream};",
                "    proxy_http_version 1.1;",
                "    proxy_set_header Host $host;",
                "    proxy_set_header X-Real-IP $remote_addr;",
                "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "    proxy_set_header X-Forwarded-Proto $scheme;",
                "    proxy_set_header X-Request-ID $request_id;",
                "}",
            ]
        )
    return "\n".join(blocks) + "\n"


def atomic_write(path: Path, data: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def serialize_config(config: configparser.ConfigParser) -> str:
    from io import StringIO

    output = StringIO()
    config.write(output, space_around_delimiters=False)
    return output.getvalue()


def configure(args: argparse.Namespace) -> None:
    source = load_config(args.source)
    worker = build_worker_config(
        source, port=args.port, firebird_host=args.firebird_host
    )
    routes = build_routes(source, args.upstream)
    atomic_write(args.worker_config, serialize_config(worker), 0o640)
    atomic_write(args.routes, routes, 0o644)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--worker-config", type=Path, required=True)
    parser.add_argument("--routes", type=Path, required=True)
    parser.add_argument("--port", type=int, default=8180)
    parser.add_argument("--upstream", default="127.0.0.1:8180")
    parser.add_argument("--firebird-host", default="127.0.0.1")
    args = parser.parse_args()
    if not 1024 <= args.port <= 65535:
        parser.error("--port must be between 1024 and 65535")
    if not re.fullmatch(r"127\.0\.0\.1:\d{2,5}", args.upstream):
        parser.error("--upstream must be a loopback IPv4 host and port")
    if args.firebird_host not in {"127.0.0.1", "localhost"}:
        parser.error("--firebird-host must be loopback")
    return args


if __name__ == "__main__":
    configure(parse_args())
